test:
  image: node:latest
  stage: test
  cache:
    policy: pull
    paths:
     - node_modules/
  script:
   - npm run test

test:karma:
  stage: test
  image: trion/ng-cli-karma
  allow_failure: false
  script:
    - ng test --code-coverage --progress false --watch false
  coverage: '/Lines \W+: (\d+\.\d+)%.*/'
  artifacts:
    paths:
     - coverage/
  tags:
    - docker

build:
  image: node:latest
  stage: build
  cache:
    policy: pull
    paths:
     - node_modules/
  script:
   - npm install --quiet
   - npm run build-prod
  artifacts:
    paths:
     - dist/